# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Pictures')),
                ('Price', models.CharField(max_length=20)),
                ('isbooked', models.BooleanField(default=False)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
    ]
