# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-26 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Price',
            field=models.CharField(max_length=20),
        ),
    ]
