# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='roomid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Rooms.Room'),
        ),
    ]
